export { default as About } from "./about/About";
export * from "./about/styled-components/about.styled";
export * from "./contact";
export * from "./contact/styled-components";
export * from "./home";
export { default as CardProject } from "./projects/components/CardProject";
export * from "./projects";
export * from "./projects/styled-components";
export { default as Skills } from "./skills/Skills";
export * from "./skills/styled-components/skills.styled";
